---
sidebar: sidebar 
permalink: concept-replication.html 
keywords: ontap, cluster, discover, manage, BlueXP, bluexp, hybrid cloud, replication policy, policy, replication, replicating, snapmirror, snapvault, data replication, fanout, cascade, source, destination, disaster recovery, DR, archive, archiving, retention, netapp replication 
summary: NetApp SnapMirror は、LAN または WAN 経由で高速にデータを複製するため、仮想環境と従来の環境の両方で高いデータ可用性と高速なデータ複製を実現します。 NetAppストレージ システムにデータを複製し、セカンダリ データを継続的に更新すると、データは最新の状態に保たれ、必要なときにいつでも利用できるようになります。外部のレプリケーション サーバーは必要ありません。 
---
= NetApp Replicationについて学ぶ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp SnapMirror は、LAN または WAN 経由で高速にデータを複製するため、仮想環境と従来の環境の両方で高いデータ可用性と高速なデータ複製を実現します。 NetApp Replicationを使用してデータをNetAppストレージ システムに複製し、セカンダリ データを継続的に更新すると、データは最新の状態に保たれ、必要なときにいつでも利用できるようになります。外部のレプリケーション サーバーは必要ありません。



[[netapp-console]]
== NetApp Console

NetApp Replicationは、NetApp Consoleからアクセスできます。

コンソールは、オンプレミスおよびクラウド環境全体にわたって、エンタープライズクラスのレベルで NetApp ストレージとデータサービスの一元管理を提供します。コンソールは、NetApp データサービスにアクセスして使用するために必要です。管理インターフェイスとして、1つのインターフェイスから多数のストレージリソースを管理できます。コンソール管理者は、企業内のすべてのシステムのストレージとサービスへのアクセスを制御できます。

コンソールの使用を開始するのに、ライセンスやサブスクリプションは必要ありません。ストレージシステムまたは NetApp データサービスへの接続を確保するためにクラウドにコンソールエージェントをデプロイする必要がある場合にのみ料金が発生します。ただし、コンソールからアクセスできる一部の NetApp データサービスは、ライセンス制またはサブスクリプション制です。

 https://docs.netapp.com/us-en/console-setup-admin/concept-overview.html["NetApp Console"]の詳細については、こちらをご覧ください。



[[features]]
== 機能

* ONTAPストレージ システム間でデータを複製し、クラウドまたはクラウド間のバックアップと災害復旧をサポートします。
* 高可用性により DR 環境の信頼性を確保します。
* ONTAP ストレージシステム間のブロックレベルの効率的なレプリケーションは高速かつ効率的で、ディザスタリカバリとバックアップの両方に対応したきめ細かなリカバリポイントを備えています。




[[cost]]
== 料金

NetApp はNetApp Replication の使用に対して料金を請求しませんが、適用されるデータの受信および送信料金についてはクラウド プロバイダーに確認する必要があります。



[[supported-systems]]
== サポートされているシステム

NetApp Replicationでは、次の種類のシステム間でのデータ レプリケーションが可能になります。

[cols="30,30"]
|===
| ソースシステム | サポートされているターゲットシステム 


| Cloud Volumes ONTAP  a| 
* Amazon FSx for ONTAP
* Cloud Volumes ONTAP
* オンプレミス ONTAP クラスタ




| オンプレミス ONTAP クラスタ  a| 
* Amazon FSx for ONTAP
* Cloud Volumes ONTAP
* オンプレミス ONTAP クラスタ




| Amazon FSx for ONTAP  a| 
* Amazon FSx for ONTAP
* Cloud Volumes ONTAP
* オンプレミス ONTAP クラスタ


|===


[[how-data-replication-works]]
== データ複製の仕組み

NetApp Replicationは、SnapMirrorとSnapVaultテクノロジーを使用して、別々のONTAPシステム上のボリューム間のデータレプリケーションを簡素化します。レプリケーションを設定するには、ソースボリュームと宛先ボリュームを特定し、レプリケーションポリシーとスケジュールを選択するだけです。

Cloud Volumes ONTAPの場合、 NetApp Replication は必要なディスクを購入し、関係を構成し、レプリケーション ポリシーを適用して、ボリューム間のベースライン転送を開始します。


NOTE: ベースライン転送には、ソース データの完全なコピーが含まれます。後続の転送にはソース データの差分コピーが含まれます。



[[supported-data-protection-configurations]]
== サポートされているデータ保護構成

NetApp Replicationは、シンプル、ファンアウト、カスケードのデータ保護構成をサポートします。

* 単純な構成では、ボリューム A からボリューム B へのレプリケーションが行われます。
* ファンアウト構成では、ボリューム A から複数の宛先へのレプリケーションが行われます。
* カスケード構成では、ボリューム A からボリューム B へ、またボリューム B からボリューム C へレプリケーションが行われます。




[[replicate-data-using-netapp-backup-and-recovery]]
== NetApp Backup and Recoveryを使用してデータを複製する

link:https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["NetApp Backup and Recovery"^]別個の ONTAP システム上のボリューム間でデータをレプリケートしながら、同じデータのバックアップをオブジェクトストレージに作成することができます。同じ ONTAP データのレプリケーションとオブジェクトへのバックアップ保護の両方を単一のサービスで管理する場合は、NetApp Backup and Recovery の使用をご検討ください。

NetApp Replicationは、Backup and Recoveryでは利用できない以下の機能をサポートしています。

* Backup and Recovery は現在、FSx for ONTAP システムとの間のデータのレプリケーションをサポートしていません。
* Backup and Recoveryでは、ボリュームのワンタイムレプリケーションの作成はサポートされていません。


さらに、レプリケーションではカスケード関係の設定が容易になります。これらの機能が必要な場合は、NetApp Replicationを使用してください。
