---
sidebar: sidebar 
permalink: task-replicating-data.html 
keywords: ontap, cluster, discover, manage, BlueXP, hybrid cloud, replication policy, policy, replication, replicating, snapmirror, snapvault, data replication, fanout, cascade, source, destination, schedule, relationship, max transfer, maximum transfer rate, rate, transfer rate, intercluster lif, replication requirement, requirements, disaster recovery, DR, archive, archiving, retention, amazon fsx for ontap, fsx for ontap 
summary: データ転送用の 1 回限りのデータ レプリケーション、または災害復旧や長期保存用の定期的なスケジュールを選択することで、 ONTAPシステム間でデータを複製できます。たとえば、災害復旧のためにオンプレミスのONTAPシステムからCloud Volumes ONTAPへのデータ レプリケーションを設定できます。 
---
= NetApp Replicationでデータレプリケーションを設定する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetAppレプリケーションを使用すると、データ転送用の 1 回限りのデータ レプリケーション、または災害復旧や長期保存用の定期的なスケジュールを選択して、 ONTAPシステム間でデータを複製できます。たとえば、災害復旧のためにオンプレミスのONTAPシステムからCloud Volumes ONTAPへのデータ レプリケーションを設定できます。



== ステップ1: データ複製要件を確認する

データを複製する前に、 Cloud Volumes ONTAP、オンプレミスのONTAPクラスター、またはAmazon FSx for ONTAPの特定の要件が満たされていることを確認する必要があります。

システム:: まだ行っていない場合は、データ レプリケーション関係のソースとターゲットのシステムを作成する必要があります。
+
--
* https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/task-getting-started-fsx.html["Amazon FSx for ONTAPシステムを作成する"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-overview-cvo.html["Cloud Volumes ONTAPシステムを作成する"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-adding-systems.html["既存のCloud Volumes ONTAPシステムを追加する"^]
* https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["ONTAPクラスタの検出"^]


--
バージョン要件:: データを複製する前に、ソース ボリュームと宛先ボリュームで互換性のあるONTAPバージョンが実行されていることを確認する必要があります。
+
--
https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html["SnapMirror関係に互換性のあるONTAPバージョンを表示する"^]

--
Cloud Volumes ONTAP固有の要件::
+
--
* インスタンスのセキュリティ グループには、必要な受信ルールと送信ルール (具体的には、ICMP とポート 11104 および 11105 のルール) が含まれている必要があります。
+
これらのルールは、事前定義されたセキュリティ グループに含まれています。

* 異なるサブネットにある 2 つのCloud Volumes ONTAPシステム間でデータを複製するには、サブネットを一緒にルーティングする必要があります (これがデフォルト設定です)。
* 異なるクラウド プロバイダーの 2 つのCloud Volumes ONTAPシステム間でデータを複製するには、仮想ネットワーク間に VPN 接続が必要です。


--
ONTAPクラスタ固有の要件::
+
--
* アクティブなSnapMirrorライセンスがインストールされている必要があります。
* クラスターがオンプレミスにある場合は、企業ネットワークからクラウド内の仮想ネットワークへの接続が必要です。これは通常、VPN 接続です。
* ONTAPクラスタは、追加のサブネット、ポート、ファイアウォール、およびクラスタの要件を満たす必要があります。
+
https://docs.netapp.com/us-en/ontap/peering/prerequisites-cluster-peering-reference.html#connectivity-requirements["ONTAPドキュメントでクラスタピアリングの前提条件を確認する"^]



--
Amazon FSx for ONTAP固有の要件::
+
--
* Cloud Volumes ONTAP が関係の一部である場合は、VPC ピアリングを有効にするか、Transit Gateway を使用して、VPC 間の接続を確保します。
* オンプレミスのONTAPクラスターが関係の一部である場合は、Direct Connect または VPN 接続を使用して、オンプレミス ネットワークと AWS VPC 間の接続を確保します。


--




== ステップ2: システム間でデータを複製する

クラウドとの間でデータを移動する際に役立つ 1 回限りのデータ レプリケーション、または災害復旧や長期保存に役立つ定期的なスケジュールを選択して、データをレプリケートできます。

.手順
. ナビゲーション メニューから、*ストレージ > 管理* を選択します。
. [システム] ページで、ソース ボリュームを含むシステムを選択し、ボリュームを複製するシステムにドラッグして、[レプリケーション] を選択します。
+
残りの手順では、Cloud Volumes ONTAPまたはオンプレミスのONTAPクラスター間の同期関係を作成する方法の例を示します。

. *ソースおよび宛先ピアリング設定*: このページが表示されたら、クラスタ ピア関係のすべてのクラスタ間 LIF を選択します。
+
クラスタ間ネットワークは、クラスタ ピアがペアワイズ フルメッシュ接続を持つように構成する必要があります。つまり、クラスタ ピア関係にある各クラスタ ペアは、すべてのクラスタ間 LIF 間で接続が確立されます。

+
これらのページは、複数の LIF を持つONTAPクラスタがソースまたはデスティネーションである場合に表示されます。

. *ソースボリュームの選択*: 複製するボリュームを選択します。
. *宛先ディスク タイプと階層化*: ターゲットがCloud Volumes ONTAPシステムの場合は、宛先ディスク タイプを選択し、データ階層化を有効にするかどうかを選択します。
. *宛先ボリューム名*: 宛先ボリューム名を指定し、宛先アグリゲートを選択します。
+
宛先がONTAPクラスタの場合、宛先ストレージ VM も指定する必要があります。

. *最大転送速度*: データを転送できる最大速度 (メガバイト/秒) を指定します。
+
転送速度を制限する必要があります。無制限のレートは、他のアプリケーションのパフォーマンスに悪影響を与える可能性があり、インターネットのパフォーマンスにも影響を与える可能性があります。

. *レプリケーション ポリシー*: 既定のポリシーを選択するか、*追加ポリシー* を選択してから、高度なポリシーのいずれかを選択します。
+
ヘルプが必要な場合は、link:concept-replication-policies.html["レプリケーションポリシーについて学ぶ"] 。

+
カスタム バックアップ (SnapVault) ポリシーを選択した場合、ポリシーに関連付けられたラベルは、ソース ボリューム上のスナップショット コピーのラベルと一致する必要があります。詳細については、link:concept-backup-policies.html["バックアップポリシーの仕組みを学ぶ"] 。

. *スケジュール*: 1 回限りのコピーまたは定期的なスケジュールを選択します。
+
いくつかのデフォルトのスケジュールが利用可能です。別のスケジュールが必要な場合は、System Manager を使用して、_destination_ クラスタに新しいスケジュールを作成する必要があります。

. *確認*: 選択内容を確認し、[実行] を選択します。


.結果
NetAppレプリケーションはデータ レプリケーション プロセスを開始します。  NetAppレプリケーションからボリューム関係の詳細を表示できます。
