---
sidebar: sidebar 
permalink: task-managing-replication.html 
keywords: replication policy, policy, replication, replicating, snapmirror, snapvault, data replication, source, destination, schedule, relationship, break, resync, max transfer, maximum transfer rate, rate, transfer rate, reverse resync, status, replication status, disaster recovery, DR, archive, archiving, retention 
summary: 2 つのシステム間のデータ レプリケーションを設定したら、 NetApp Replicationからデータ レプリケーションのスケジュールと関係を管理できます。 
---
= NetApp Replicationでデータレプリケーションを管理する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
2 つのシステム間のデータ レプリケーションを設定したら、 NetApp Replicationからデータ レプリケーションのスケジュールと関係を管理できます。

.手順
. link:task-login-replication.html["NetApp Replicationにログイン"] 。
. データ レプリケーション関係のステータスを確認し、正常であることを確認します。
+

NOTE: 関係のステータスがアイドルで、ミラー状態が初期化されていない場合は、定義されたスケジュールに従ってデータ レプリケーションが実行されるように、宛先システムから関係を初期化する必要があります。 System Manager またはコマンドライン インターフェイス (CLI) を使用して関係を初期化できます。これらの状態は、宛先システムに障害が発生し、その後オンラインに戻ったときに発生することがあります。

. ボリューム関係のアクション メニューを選択し、使用可能なアクションの 1 つを選択します。
+
次の表では、利用可能なアクションについて説明します。

+
[cols="15,85"]
|===
| アクション | 説明 


| 情報 | ボリューム関係の詳細（転送情報、最終転送情報、ボリュームの詳細、関係に割り当てられた保護ポリシーに関する情報）を表示します。 


| 解除 | ソース ボリュームと宛先ボリュームの関係を解除し、データ アクセス用に宛先ボリュームをアクティブ化します。このオプションは通常、データの破損、誤った削除、オフライン状態などのイベントによりソース ボリュームがデータを提供できない場合に使用されます。https://docs.netapp.com/us-en/ontap-sm-classic/volume-disaster-recovery/index.html["ONTAPドキュメントで、データアクセス用に宛先ボリュームを設定し、ソースボリュームを再アクティブ化する方法について学習します。"^] 


| 再同期  a| 
ボリューム間の壊れた関係を再確立し、定義されたスケジュールに従ってデータのレプリケーションを再開します。


NOTE: ボリュームを再同期すると、宛先ボリュームの内容がソース ボリュームの内容によって上書きされます。

逆再同期（宛先ボリュームからソースボリュームにデータを再同期する）を実行する方法については、 https://docs.netapp.com/us-en/ontap-sm-classic/volume-disaster-recovery/index.html["ONTAPのドキュメント"^] 。



| 逆再同期 | ソース ボリュームと宛先ボリュームの役割を逆にします。元のソース ボリュームの内容は、宛先ボリュームの内容によって上書きされます。これは、オフラインになったソース ボリュームを再アクティブ化する場合に役立ちます。最後のデータ複製からソース ボリュームが無効になった時点までの間に元のソース ボリュームに書き込まれたデータは保持されません。 


| スケジュールを編集 | データ複製の異なるスケジュールを選択できるようになります。 


| 最大転送速度を編集 | データを転送できる最大速度 (キロバイト/秒) を編集できます。 


| 更新 | 増分転送を開始して、宛先ボリュームを更新します。 


| 削除 | ソース ボリュームと宛先ボリューム間のデータ保護関係を削除します。これにより、ボリューム間でデータのレプリケーションは行われなくなります。このアクションでは、データ アクセス用の宛先ボリュームはアクティブ化されません。 
|===


.結果
アクションを選択すると、 NetApp Replication関係またはスケジュールが更新されます。
